### ISSUE TITLE
publish this to bower and npm?

### ISSUE THREAD

**Issue by stevemao** [tommoor/tinycon#70]

**Comment by fedosov** [comment]
:+1:

**Comment by constellates** [comment]
![image](https://cloud.githubusercontent.com/assets/4325905/13861387/481e10ac-ec4a-11e5-9668-0dd56213f612.png)
I would also love to see this published to npm in particular. I'm currently using the git url in a package.json file as an alternative. However I seem to be unable to link to specific releases and I believe this is due to the fact that the release don't contain the package.json file.

**Comment by stevermeister** [comment]
:+1:

**Comment by stevermeister** [comment]
ok, it looks like author is not going to do this.

forked https://github.com/stevermeister/tinycon2
and published on npm 
`npm install tinycon2`

**Comment by tommoor** [comment]
I would suggest using the git url instead of npm - both the packages that have been published there are not under my control :information_desk_person: 

You can easily point at a tag or commit using the github url.
